typography_spectrum: 0.026233767857775092
color:
  brandStrength: 0.13387036183848977
  lightness: 0.5995973669923842
  saturation: 0.7187374813947827
  rhythmicContrast: 0.9523321327287704
  brandColors:
    - '#10222B'
    - '#95AB63'
    - '#BDD684'
    - '#E2F0D6'
    - '#F6FFE0'
layout_spectrum: 0.7615641157608479
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8c029fb0-7a23-437b-b226-dd1cd268051d.png
name: DesignFarm
navigation:
  - id: 'https://thegrid.ai/designfarm/home/'
    url: 'https://thegrid.ai/designfarm/home/'
    name: Home
    type: external
  - id: 'https://thegrid.ai/designfarm-logos/'
    url: 'https://thegrid.ai/designfarm-logos/'
    name: Logos
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fccb7877-6d2a-4b18-b4f8-dd9df3cbe008.ico
